#include <iostream>

#define LONG_RUNNING_COUNTER 10'000'000

// EXPLANATION:
// - If intern implemented sensor class as a set of virtual functions this will have the following problems:
// 1. High cost of devirtualization due to the need to go through pointer dereferencing
// 2. Cannot be inlined easily unless final word is added everywhere. Inlining functions is one of the major efficiency gains in C++ code
// 3. Holding massive vTables means we might lose lower bit padding effectively causing cache misses due to higher memory requirement

// Part A - Runtime polymorphism
// - Abstract class because contains one pure virtual function
// - Serves as a template (we cannot create instances of the Sensor)
// - resolved at runtime because of the devirtualization (vPtr dereference)
// - value_ must be protected (not private) because child functions that override parent's functions cannot access private variables of the parent. Compilers create boundary between classes during inheritence so that private members of the parent class can be accessed only by functions in the parent class
class Sensor {
protected:
    float value_;
public:
    virtual ~Sensor() { std::cout << "Base sensor destructor" << std::endl; }
    [[nodiscard]] virtual float read() const = 0;
};

class IMUSensor : public Sensor {
public:
    ~IMUSensor() { std::cout << "IMU destructor" << std::endl; }
    [[nodiscard]] float read() const override { return 3.14; }
};

class EncoderSensor : public Sensor {
public:
    ~EncoderSensor() { std::cout << "Encoder destructor" << std::endl; }
    [[nodiscard]] float read() const override { return 2.28; }
};

// Part B - Static Polymorphism
// - No virtual functions or vTables
// - Uses templates thus resolved at compile time
// - No vPtr and no vTable means small memory footprint
// - Destructors behave like during the standard inheritance but without virtual
// - Base class destructor should be protected to signal developers this is supposed to be inherited and inherited class should not be destroyed using base class
// Unlike with virtual destructors using base destructor will cause undefined behavior
// SensorBase<IMU>* imu_ptr = new IMU();
// delete imu_ptr; // undefined behavior, do not do this
template <typename DerivedSensor>
class SensorBase {
protected:
    float value_;
    ~SensorBase() { printf("SensorBase destructor\n"); }
public:
    [[nodiscard]] float read() const {
        return static_cast<const DerivedSensor*>(this)->read_impl();
    };
};

class IMU : public SensorBase<IMU> {
public:
    ~IMU() { printf("Static IMU destructor\n"); }
    [[nodiscard]] float read_impl() const { return 3.14f; }
};

class Encoder : public SensorBase<Encoder> {
public:
    ~Encoder() { printf("Static Encoder destructor\n"); }
    [[nodiscard]] float read_impl() const { return 2.28f; }
};

// Part C - Questions
// Question 1:
// It costs dereference time itself, but also time wasted by the CPU branch predictor.
// - lookup of the vTable takes time because it is not located in the CPU cache.
// - branch prediction time. When CPU branch predictor cannot predict an indirect branch target from a pointer-indexed table, branhc mispredicts, CPU flushes the prediction pipeline. Target function may not be in the L1 instruction cache (cache miss) and routes to many different implementations.
// At 1kHz ideally we need to keep things as close to CPU as possible, thus every lookup beyond CPU cache in the RAM (swap should be disabled, so RAM is the last resort for real-time critical systems) might be too slow
//
// Question 2:
// The vTable: This is an array of function pointers generated by the compiler at compile time. It is typically stored in a global, read-only data segment of your program's memory (such as the .rodata section). Because of this every lookup of that vTable is not desirable in the time critical systems
// vPtr is stored at the start of the memory section occupied by the class instance. On the 64-bit systems vPtr is 8 bytes meaning 32-bit padding cannot be applied to the virtual class instances on the 64-bit system
//
// Question 3:
// Runtime dispatch has the following benefits: reduced compilation time (minimal benefit IMO, because in C++ compilation is the step where we should offload as much logic as possible to create compile-time guarantees), ABI stability (e.g. binary will not be affected by OS libraries), delay execution of certain code. Most importantly virtual classes can all be treated as the base class.
// I think ABI stability is the key here. New versions of your library have to be linkable with other apps originally compiled with older versions of your library. Also, library needs to be distributed (and updated) independently from apps based on it
// Thus, realistic scenario is something that is not performance critical (not hardware-centric code). I can think of communication infrastructure (e.g. DDS wrappers which are not the RT critical path) or computer vision libraries. We treat convenience of development and ABI stability for the performance optimizations
//
// Question 4:
// Compiler can prove the resolution from the base type all the way to concrete type. Virtual dispatch is replaced with the direct call.

int main(/*int argc, char * argv[]*/) {
    // Part A
    // Example of why Sensor sensor cannot be created because it is abstract class
    // main.cpp:38:12: error: cannot declare variable ‘sensor’ to be of abstract type ‘Sensor’
    //Sensor sensor;
    IMUSensor imu_;
    EncoderSensor enc_;

    // Part B
    IMU static_imu_;
    Encoder static_enc_;
    printf("IMU: %f / Encoder: %f\n", static_imu_.read(), static_enc_.read());

    return 0;
}

